language: python
git:
  depth: 3
  lfs_skip_smudge: true
  submodules: false
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
  - pypy
  # - pypy3
matrix:
  include:
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
      python: 2.7
      before_install: pyenv install 2.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
      python: 3.5
      before_install: pyenv install 3.5.0
  allow_failures:
    - os: osx
    - python: 2.6
    - python: 3.7-dev
    - python: nightly
    - python: pypy
    # - python: pypy3
  fast_finish: true
cache: pip
install:
  - pip install -U setuptools
  - pip install -U tox
  - pip install tox-travis
script: tox --skip-missing-interpreters
after_script:
  - tox -e check
  - tox -e dups
  - tox -e pylint -- -E
before_deploy:
  - test $TRAVIS_TEST_RESULT -eq 0
  - test $TRAVIS_OS_NAME = linux
deploy:
  - provider: pypi
    user:
      secure: "UFT4XmfVNmGg54ul0qoIbQ1w3ijGJ6nzCrkV+rozbAia25hzoHn09j5hY7zC1grqNsaU7J7LT0FNzWBhZ5PHyBXKed1eh7yAx4hDpVGfKpTfOMumdL4XKOhMTTXqG6f91/4GpCA+BXaJspNv/g2sAG4lEWAcOIgIup5+39ZkSr+Us+Wh7G1Md/pVttwk49aME5RKkQRMhLFwjxV0k0EZSv/y4xW0+ZYiJMrtBgc5F9BkS95DU6jE+lugsZdN3DJmEiH4aVNWsZafDhG374Rb+iidkRK5EKK4Hk/OostyTS1v4ltCCSMnGy0Aqus4Try8dL7QPiyf9aXdZqopMvnXJDlyOjO53dBR8aLJjyuCBPQhQiexX6sAVn3gTllMTgX3knPygFuJ3XQKeFPZps+6CPr+fKggYIqEQuTiOSYNC9MFBjhxR3/tGbMp9PlbIcySxdt0vqgUWoqUWT29D8wQ8GZ4KM0BPGg4ozWhwtPKEMkDL2wLGzsraBEpb2M06UurOdXd9mYPffqmWBxnTZPy9EcM9NeLt/yzke5bbIxBhQiEkKlhQWzFoQejZaNTWOFmNB4QC55jphVGl8wQF1cT8uv1p2OLbZTKdx/Cv/LP/Q7yZRgbJEBF1g7Eq5uLjVGAerqEpfSx2dSV+Bt4PHydZHonH0UDIASaOE4Mw09wDWQ="
    password:
      secure: "qXCbjA8OudvSGb3SegHBgPFNrS8rjvCsf1fnTTRW9EKabw+P7z5Ulqgmxha9g2TCZgeA8nMNDpcQGmSC2M4vvl4gQeqT4/OzE+ij1HSSE8BG35mGJjMgirsOJgmTXCiiBoBjLZfzWGTR2UuveBw0VcjLukxE1y3hrUd1o13pu/ox4jKeLEh4PJEST/KRL0tYrwFXOGDCToR3LML9x4LqvRiUwW09MyyqG+J4rXbsHv9GMxAgINyplSOaV36SFaWwVNjUE9lJgGN/1jFZ1u6MA+eFW9v/ABpA5uKIt2L6HdUuRuciGZIFDXeZe2pJyUyZ9laa7+O0UQDtvZl3HRZTb+amKBOB1WcNsEYf9ShzopFufxp9xnqfqUekof3kBAjJwC0MOhN3eEEAhr6tplOe+rM7XcddjYc63jJMTIcY5cw2eVb42xMn1ScXQ4C7PavAqZvDsrD6JVyWVidatU3DBHTbUSe5VMbEmIu1QRaIEIG29D5/gbwAg61SqXIv+xFPpQdhaE0swh3Dp4y7aTHNjWak+nOXJMzbVO3/AWCDPTR0BD/UCR1SV0X3vJ8Kr3AZpY0ewXP7ota/o+gGBQJmSV/GxUSSwnhunfDp9pTN0dI+Dm8lU1clsiY4MdV5ePxu46oc8V0oV5+J+ilwtucDH/S0UeKjKi5qnqh7cFXw5NM="
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    on:
      python: 3.5
      tags: true
  - provider: releases
    api-key:
      secure: "Y/ndK4WbYjBY5HDKCU2nC2ulzVHzmcXyUCtx22PuVOffZJQ/qjHWd174nesksUrsnrfk2PA6mBIsn9+xyqoAYKSLU6GIYuvfJIUS69y+er4SgMayD9SCiUhSevY3gR+79yluUNyZBiXO0Od7p3v7lA1V1TKhtuMi67jSdBQRkao+kA5+Dd1z/QrzpvPZAwW5F1mlSuSMsmKYK+S4RD+khbkP+/buX8sQMvpulD6UO8SeTo2t4+NAtCmY0ePN18Q57Vr12AP+9nezVVfSjVZMIapdRohDMlwpz5CpBGwR42KNHCSuqnQnt4urgeF1EQjBLxr7I+lftNnw2t+aWJzainMXWLeV1bNWYi/PDlFoW4cpmhUfbnpxhB13yj5/BC6BPWzdNpPtWo9lWKIa2pGzI9zv0wlYp+pWZV1vbS6+lzAuJ9jwMv4jmFiaxnJhYMtq9dai5tc+37azOEn2BotRzD3TBV2BGxgrGeh5kxQavhzGCba+qzqFdL3BH8mQaksbw8P7r1PyERZmf8SMeDbvnTcvg+3Hiw5+mg50ybXiZ6Adu4QRbxVugJlhIBkkp1r0rxc5G4h57HU4rtRNTSEk01ybt8X/QAs0AqVrvXYMx60OkPwAWn/KiEYyiNO5eQmOPlHdBAnIOGt0gcCGtCoe+ep00EAq4ho0up5X0Xe1mI4="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      python: 3.5
      tags: true
      name: "${$TRAVIS_REPO_SLUG#*/} ${$TRAVIS_TAG#v}"
      body: "## Changelog"
